# Generated by Django 2.2.6 on 2021-08-06 23:27

import BOOKS.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='Enter Book Name', max_length=100)),
                ('author_name', models.CharField(default='Enter Author Name', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('thumbnail_2', models.ImageField(blank=True, upload_to='')),
                ('book_pdf', models.FileField(blank=True, upload_to='', validators=[BOOKS.validators.validate_file_size])),
                ('synopsis', models.TextField(default='Enter Synopsis')),
                ('review', models.TextField(default='Enter Review')),
                ('category', models.CharField(choices=[('fe', 'featured'), ('n', 'normal')], default='n', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Romance', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, default='Yet to be reviewed', max_length=500)),
                ('review_name', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('book_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='BOOKS.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_genre',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='BOOKS.Genres'),
        ),
    ]
