# Generated by Django 2.2.6 on 2021-08-03 16:47

import BOOKS.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='Enter Book Name', max_length=100)),
                ('author_name', models.CharField(default='Enter Author Name', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('thumbnail_2', models.ImageField(blank=True, upload_to='')),
                ('book_pdf', models.FileField(blank=True, upload_to='', validators=[BOOKS.validators.validate_file_size])),
                ('synopsis', models.TextField(default='Enter Synopsis')),
                ('review', models.TextField(default='Enter Review')),
                ('category', models.CharField(choices=[('fe', 'featured'), ('n', 'normal')], default='n', max_length=50)),
                ('sub_category', models.CharField(choices=[('r', 'romance'), ('d', 'drama'), ('c', 'comedy'), ('t', 'thriller'), ('cr', 'crime'), ('h', 'horror'), ('s', 'soothing/religious')], default='r', max_length=50)),
            ],
        ),
    ]
