# Generated by Django 2.2.6 on 2021-08-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKS', '0002_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BOOKS.Genres'),
        ),
    ]
