# Generated by Django 2.2.6 on 2021-08-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKS', '0003_book_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(default='Romance', max_length=50),
        ),
    ]
