# Generated by Django 2.2.6 on 2021-08-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKS', '0005_auto_20210804_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, default='Yet to be reviewed', max_length=500)),
                ('review_name', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('book_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='BOOKS.book')),
            ],
        ),
    ]
